//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirPortWebApi.Data.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public int SectionId { get; set; }
    
        public virtual SectionTable SectionTable { get; set; }
        public virtual StatusType StatusType { get; set; }
    }
}
